version: '3'

services:
  api-habilitacion-replica1:
    image: api_habilitacion:${TAG}
    container_name: api-habilitacion-replica1
    ports:
      - "6060:5050"  # Puedes ajustar el mapeo de puertos según tus necesidades
    expose:
      - 6060
    environment:
      - JAVA_OPTS=-Xmx4g  # Asigna 4 GB de memoria al heap de Java
    restart: always  # Configura para reiniciar siempre que caiga
    command: -p 6060
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    networks:
      - my-habilitacion

    api-habilitacion-replica2:
    image: api_habilitacion:${TAG}
    container_name: api-habilitacion-replica2
    ports:
      - "6061:5050"  # Puedes ajustar el mapeo de puertos según tus necesidades
    expose:
      - 6061
    environment:
      - JAVA_OPTS=-Xmx4g  # Asigna 4 GB de memoria al heap de Java
    restart: always  # Configura para reiniciar siempr    :
    command: -p 6061
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    networks:
      - my-habilitacion
      
  nginx-expuesto:
    build: ./nginx-expuesto.conf
    ports:
      - "5050:80"
    restart: always
    networks:
      - my-habilitacion
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    depends_on:
      - api-habilitacion-replica1
      - api-habilitacion-replica2
